import json
from datetime import datetime
from pathlib import Path

# Load config
config_path = Path("C:/Users/Steve/Documents/github/proxmox-homelab/automation/obsidian_helpers/obsidian_helpers_config.json")
with config_path.open("r") as f:
    cfg = json.load(f)

# Setup paths
vault_root = Path(cfg["vault_root"])
projects_dir = vault_root / cfg["projects_folder"]
changelog_path = vault_root / cfg["changelog_path"]

# Create a new project summary
project_name = "example_test_project"
summary_file = projects_dir / f"{project_name}.md"
summary_content = f"""# 📁 Project: {project_name.replace('_', ' ').title()}

**Created:** {datetime.now().strftime('%Y-%m-%d')}

**Description:**  
This is a test summary generated by the automation system to validate pathing and config.

**Location:** proxmox-homelab/{project_name}/
"""
projects_dir.mkdir(parents=True, exist_ok=True)
summary_file.write_text(summary_content.strip(), encoding='utf-8')

# Append changelog entry
timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
changelog_entry = f"""## [init] - {timestamp}
🧪 Initialized test project `{project_name}` and created corresponding Obsidian summary.
"""

if not changelog_path.exists():
    changelog_path.parent.mkdir(parents=True, exist_ok=True)
    changelog_path.write_text("# 📋 Changelog\n\n", encoding='utf-8')

with changelog_path.open("a", encoding='utf-8') as f:
    f.write("\n" + changelog_entry.strip() + "\n")

print(f"✅ Created: {summary_file}")
print(f"✅ Updated: {changelog_path}")